language: python

python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev"
  - "nightly"

install:
  - python setup.py install
  - pip install -U git+git://github.com/python/mypy
  - pip install flake8

script:
  - mypy --disallow-untyped-calls --disallow-untyped-defs --check-untyped-defs burp
  - flake8 burp
